### ISSUE TITLE
Specify how much current is needed in the manual

### ISSUE THREAD

**Issue by geoffrey-eisenbarth** [Morningstar-Engineering/MC6-Midi-Controller#1]
Is it possible to specify how much current should be supplied to the MC6 in the "Powering Up the MC" section of the manual? I'm currently in a situation where I might need to daisy chain an output of my power supply to power the MC6 and knowing this information would be useful. My apologies if it's listed somewhere, but my searches through the manual and website haven't pulled anything up.

**Comment by tyzjames** [comment]
Hi, thanks for raising this. We have added the information. The MC6 requires at least 80mA.
